### ISSUE TITLE
iPhone 14 Pro Max's rear camera is not reading the barcode

### ISSUE THREAD

**Issue by Tesfaye-Eshetie** [Dynamsoft/barcode-reader-javascript-samples#99]
I have a problem with the iPhone 14 Pro Max's rear camera; it is not focusing to read the barcode, but the front camera is working just fine. I have a user report about this; are there any solutions? I used the "dynamsoft-javascript-barcode" version 9.6.0 for building the app.

**Comment by Keillion** [comment]
Sorry for the late reply due to my vacation.

Safari of iPhone does not provide a focus API, so we always rely on the default behavior of the browser.

Most of the inability to focus is because the camera is too close to the object. You can use [the region API](https://www.dynamsoft.com/barcode-reader/docs/web/programming/javascript/user-guide/advanced-usage.html?ver=latest#read-a-specific-arearegion) to guide the user to place the target at an appropriate distance.

When you set a region, there will be a rectangle on the canvas cover the video.

**Comment by Tesfaye-Eshetie** [comment]
@Keillion Thank you very much. My question is this: I have a PWA app that uses a Dynamsoft Barcode Reader. And the Dynamsoft Barcode Reader works in every iPhone except the iPhone 14 Pro Max's rear camera. I've also configured the region API. In addition, it is not reading on the "https://demo.dynamsoft.com/barcode-reader-js/common-oned-twod.html" demo using the same phone.

**Comment by Keillion** [comment]
@Tesfaye-Eshetie  

Only iPhone 14 Pro Max's rear? Strange.

I'll go to apple store to have a test.

**Comment by Keillion** [comment]
I reproduced the issue on an iPhone 14 Pro Max. And I confirmed that Safari does not open new focus-related APIs.

I googled this issue and found that it is a common phenomenon and is an issue introduced with newer versions of iPhone/iOS.

You can use [singleFrameMode](https://www.dynamsoft.com/barcode-reader/docs/web/programming/javascript/api-reference/BarcodeScanner.html?ver=latest#singleframemode) as a fallback to alleviate this problem.
e.g.
code: https://github.com/dynamsoft-rd-0/dbrjs-mass-samples/blob/master/not-focus-so-single-frame-mode.html
run: https://dynamsoft-rd-0.github.io/dbrjs-mass-samples/not-focus-so-single-frame-mode.html

**Comment by Keillion** [comment]
In dbrjs v9.6.20, the logic of selecting the camera in the iOS environment has been changed. Normal lenses are now preferred over wide-angle lenses.

After testing, it works well in the latest system of iphone 14 pro max.
